"""initial

Revision ID: 766de944aad8
Revises: 
Create Date: 2025-05-25 14:50:09.177027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '766de944aad8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('link', sa.String(length=200), nullable=False),
    sa.Column('category', sa.Enum('Positif', 'Negatif', 'Netral'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('training',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('Positif', 'Negatif', 'Netral'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('testing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('Positif', 'Negatif', 'Netral'), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('testing')
    op.drop_table('training')
    op.drop_table('post')
    # ### end Alembic commands ###
