"""empty message

Revision ID: 838d98168a29
Revises: 4b6e48507910
Create Date: 2025-06-08 15:05:01.009106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '838d98168a29'
down_revision = '4b6e48507910'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('testing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('testing', schema=None) as batch_op:
        batch_op.drop_column('username')

    # ### end Alembic commands ###
